import os

PROFILE_TECHNOPARK43 = "technopark43"
PROFILE_TECHNOPARK46 = "technopark46"
PROFILE_TECHNOPARK42 = "technopark42"
PROFILE_TECHNOPARK11 = "technopark11"
PROFILE_TECHNOPARK12 = "technopark12"
PROFILE_TECHNOPARK13 = "technopark13"
PROFILE_TECHNOPARK14 = "technopark14"
PROFILE_TECHNOPARK19 = "technopark19"
# PROFILE_PASSWORD = os.environ['PROFILE_PASSWORD']
PROFILE_PASSWORD = "testQA1"

PROFILE_TECHNOPARK11_ABOUT_PAGE = "/bochrvf260602.lp/about"