import os

PROFILE_TECHNOPARK55 = "technopark55"
PROFILE_TECHNOPARK46 = "technopark46"
PROFILE_PASSWORD = os.environ['PROFILE_PASSWORD']
FAKE_CURRENT_PASSWORD = "test12"
NEW_PASSWORD = "test34"
FAKE_RETYPE_PASSWORD = "test43"
UNALLOWED_PASSWORD = "<script>"
PAGE_TECHNOPARK55 = "/technopark55"
