BASE_URL = "https://redioteka.com/"
TITLE_OF_LOGIN_PAGE = "Вход"
ID_OF_MOVIE = "7"
ID_OF_ACTOR = "1"
ID_OF_PAID_MOVIE = "92"
TITLE_OF_PROFILE_PAGE = "Настройки профиля:"
UMONEY_URL = "https://yoomoney.ru/quickpay/confirm.xml"
ERROR_MSG_OF_INVALID_UPD_LOGIN = 'Логин должен содержать только латинские буквы и цифры'
ERROR_MSG_OF_EMPTY_UPD_LOGIN = 'Это поле обязательно к заполнению'
ERROR_MSG_OF_INVALID_UPD_EMAIL = 'Введен некорректный email'
ERROR_MSG_OF_EMPTY_UPD_EMAIL = 'Это поле обязательно к заполнению'
LEN_OF_HREF_WITHOUT_ID = 7
