BASE_URL = "https://redioteka.com/"
TITLE_OF_LOGIN_PAGE = "Вход"
ID_OF_MOVIE = "7"
ID_OF_ACTOR = "1"
ID_OF_PAID_MOVIE = "92"
TITLE_OF_PROFILE_PAGE = "Настройки профиля:"
UMONEY_URL = "https://yoomoney.ru/quickpay/confirm.xml"
ERROR_MSG_OF_INVALID_UPD_LOGIN = 'Логин должен содержать только латинские буквы и цифры'
ERROR_MSG_OF_INVALID_SIGNUP_LOGIN = 'Логин должен содержать только латинские буквы и цифры'
ERROR_MSG_OF_EMPTY_UPD_LOGIN = 'Это поле обязательно к заполнению'
ERROR_MSG_OF_INVALID_UPD_EMAIL = 'Введен некорректный email'
ERROR_MSG_OF_INVALID_SIGNUP_EMAIL = 'Введен некорректный email'
ERROR_MSG_OF_EMPTY_UPD_EMAIL = 'Это поле обязательно к заполнению'
ERROR_MSG_OF_EMPTY_SIGNUP_FIELD = 'Это поле обязательно к заполнению'
ERROR_MSG_OF_LEN_PASSWORD_SIGNUP = 'Пароль должен быть длиной от 8 до 50 символов'
ERROR_MSG_OF_DIFFERENT_PASSWORDS_SIGNUP = 'Пароли не совпадают!'
LEN_OF_HREF_WITHOUT_ID = 7
DEFAULT_AVATAR = 'https://redioteka.com/assets/profile.webp'
INVALID_AVATAR = '/resources/invalid_avatar.jpeg'
INVALID_EMAIL = 'invalidemailcom'
WRONG_PASSWORD = 'random_password'
REDIOTEKA_BASE_URL = 'https://redioteka.com/'
SEARCH_MOVIE_TITLE = 'Гнев человеческий'
SEARCH_ACTOR_NAME = 'солейл мун фрай'
SEARCH_LETTER = 'г'
SEARCH_TWO_LETTERS = 'гн'
VALID_SIGNUP_LOGIN = 'newlogin'
INVALID_SIGNUP_LOGIN = 'newlogin@@'
INVALID_SIGNUP_EMAIL = 'newemai$$l@mail.ru'
INVALID_SIGNUP_PASSWORD = '1'
CONFIRM_INVALID_SIGNUP_PASSWORD = '2'
VALID_SIGNUP_EMAIL = 'newemail@mail.ru'
SIGNUP_PASSWORD = 'qwerty123'
SIGNUP_CONFIRM_PASSWORD = 'qwerty1234'
BIG_SIGNUP_PASSWORD = 'qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm'
SMALL_SIGNUP_PASSWORD = 'small'
INVALID_LETTER_SIGNUP_LOGIN = 'q'
INVALID_NUMERIC_SIGNUP_LOGIN = '1234'
INVALID_CYRILIC_SIGNUP_LOGIN = 'Никитосич'
PATH_OF_DEFAULT_AVATAR = '/resources/default_avatar.webp'
PATH_OF_VALID_AVATAR = '/resources/valid_avatar.webp'
NEW_VALID_EMAIL = 'newvalidemail@mail.ru'
NEW_VALID_LOGIN = 'newvalidlogin'
