from tests.folder_tests import FolderTests
from tests.trash_bin_tests import TrashBinTests
from tests.history_tests import HistoryTests
from tests.work_with_files_tests import WorkWithFilesTests
from tests.directories_test import DirectoryTest
from tests.sort_and_filter_test import SortAndFilterTest
from tests.creating_document_test import CreatingDocumentsTest
from tests.tabs_at_home_test import TabsAtHomePageTest
