from tests.directories_test import DirectoryTest
from tests.sort_and_filter_test import SortAndFilterTest
from tests.creating_document_test import CreatingDocumentsTest
from tests.tabs_at_home_test import TabsAtHomePageTest
