# -*-coding: utf-8-*-

WAITING_TIME = 5
WAITING_TIME_LONG = WAITING_TIME * 5

ENTRY_POINT = "https://ok.ru/"
DEFAULT_PATH = ''

TEST_DIR = 'tests'

TEST_LOGIN = 'technopark51'
TEST_PASSWORD = 'testQA1'

SELENIUM_GRID_HUB_ADDRESS = 'http://127.0.0.1:4444/wd/hub'

PREFERRED_BROWSER_KEY = 'PREFERRED_BROWSER'

PREF_CHROME = 'CHROME'
PREF_FIREFOX = 'FIREFOX'
