from .achievements import AchievementsPage
from .create_product import CreateProductPage
from .main import MainPage
from .product import ProductPage
from .registration import RegistrationPage
from .reviews import ReviewsPage
from .search import SearchPage
from .seller_products import SellerProductsPage
from .user_chats import UserChats
from .user_favorites import UserFavoritesPage
from .user_products import UserProductsPage
from .user_settings import UserSettingsPage
from .favorites import FavouritesPage
from .comments import CommentsPage
from .await_reviews import AwaitReviewsPage
from .messages import MessagesPage
