from .achievements import AchievementsPage
from .create_product import CreateProductPage
from .main import MainPage
from .product import ProductPage
from .registration import RegistrationPage
from .reviews import ReviewsPage
from .search import SearchPage
from .seller_products import SellerProductsPage
from .user_favorites import UserFavoritesPage
from .user_products import UserProductsPage
from .user_settings import UserSettingsPage
from .user_favorites import UserFavoritesPage
from .user_await_reviews import UserAwaitReviewsPage
from .user_messages import UserMessagesPage
from .edit_product import ProductEditPage
